### ISSUE TITLE
[FEATURE]Can you create a discord group?

### ISSUE THREAD

**Issue by martjay** [sdatkinson/NeuralAmpModelerPlugin#105]
Can you create a discord group? I just applied for a Facebook account and the next day it was blocked

**Comment by David-Else** [comment]
If users would like a proper free open source discussion group with the best features, please use [Matrix](https://matrix.org/). Many people boycott Facebook for very good reasons. Matrix is a better choice than Discord for these reasons: https://joinmatrix.org/guide/matrix-vs-discord/

Matrix has a great chat app called [Element](https://element.io/) that can be run in your browser, or downloaded for Mac/Win/Linux/Android. Thunderbird email software even has Matrix built in now, it is the future, Facebook is garbage!

**Comment by martjay** [comment]
> 

Facebook is garbage! I agree. Facebook is full of discrimination and politics.

**Comment by David-Else** [comment]
There is no Matrix group yet, I think it would be up to the maintainers to create an official one.

**Comment by DrConflict** [comment]
I figured there would be a Matrix group to share snapshots people made. But this project is beta currently and I assume most people don't even know this exists yet. I hope the devs consider making a Matrix group though.

**Comment by hrstoyanov** [comment]
Not sure we need another forum! GitHub has a "discussion" feature that can be enabled by the admin @sdatkinson . Then  this repo becomes just like any other online forum. This is necessary, and should be done sooner rather than later, otherwise discussions, QandA, etc will result in GitHub issues,  mixed up with real issues. Read the help on "GitHub discussions".

**Comment by David-Else** [comment]
Definitely enable discussions, but the problem is there is no sticky feature so threads featuring links to `.nam` files would soon get pushed down out of view in the general chit chat. If a special catagory for `.nam` files was created it could work: https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions

**Comment by martjay** [comment]
> Not sure we need another forum! GitHub has a "discussion" feature that can be enabled by the admin @sdatkinson . Then this repo becomes just like any other online forum. This is necessary, and should be done sooner rather than later, otherwise discussions, QandA, etc will result in GitHub issues, mixed up with real issues. Read the help on "GitHub discussions".

github's discussion forum is mainly used for feedback questions, for sharing files is very inconvenient

**Comment by martjay** [comment]
I think Discord is very suitable, many projects are using, it is more powerful than the forum, and even live stream, can publish a variety of files.

**Comment by DrConflict** [comment]
A Matrix/Discord group would make most sense for exchanging files without a doubt. Using github for this would make no sense.

**Comment by sdatkinson** [comment]
I believe there are some unofficial Discord groups that are now in existence.

I'm not personally keen on admin-ing them at the moment so that I can keep my focus a bit more narrow and spend more time on the "fun" parts of the project, so I'm going to mark this as resolved, assuming where we've gotten to now works for you?
