### ISSUE TITLE
Some UI suggestions

### ISSUE THREAD

**Issue by DrConflict** [sdatkinson/NeuralAmpModelerPlugin#115]
Since NAM is still in beta, these are not going to be priorities for now. But I hope these suggestions can be considered for the future. Thanks!

-Double clicking knobs resets them to default position
-Clicking the values under the knobs lets us input values with the keyboard
-Holding shift (or another modifier) lets us have finer control when using the mouse to turn knobs
-Scalable vector based UI or several percentage options to resize the UI
-Preset manager/browser

**Comment by sdatkinson** [comment]
> -Double clicking knobs resets them to default position

This should already happen.

> -Clicking the values under the knobs lets us input values with the keyboard
> -Holding shift (or another modifier) lets us have finer control when using the mouse to turn knobs

I can check whether the iPlug2 framework supports these, but if not, then it's not something I'd be developing under this repo.

> -Scalable vector based UI or several percentage options to resize the UI

Hmm, I thought this was supposed to happen. Worth a bug report if not.

> -Preset manager/browser

Check the other Issues; I believe there's already a feature request or two along these lines.

---

Closing since the bullets all have answers. If the last two deserve their own bug reports/feature requests, please open those separately so I can track them separately.  Thanks!
