### ISSUE TITLE
Aliasing[BUG]

### ISSUE THREAD

**Issue by ArtemBankin** [sdatkinson/NeuralAmpModelerPlugin#134]
I noticed heavy aliasing artefacts almost on every capture ....on high pitched notes ..with higain ...
the developer needs to implement anti-aliasing filters in the plugin, but given that the plugin is already very cpu heavy, it will not be easy to do.

[heavy aliasing .zip](https://github.com/sdatkinson/NeuralAmpModelerPlugin/files/11039615/heavy.aliasing.zip)

**Comment by jonlinnarson** [comment]
Are you sure that you are not hitting the plug-in input to hard? The only way I can recreate your problem is by absolutely slamming the input of the plug-in. Try lowering the input before the plug-in, or with the input gain control, so that the input meter is not hitting the roof when you are strumming hard (think of it the same way as when you are connecting the guitar straight into your interface DI, you don't want the signal to clip anywhere). See if that helps. 

Btw, the input gain control is not meant to be a control for the amount of amp distortion, it's just a way to gain-stage like in any other plug-in.

If this is also a problem with models you have made yourself, make sure that none of the material you have trained NAM with is digitally clipping anywhere. This will definitely impact the resulting model.

**Comment by ArtemBankin** [comment]
Nope - pushing outuput providing aliasing . not input ....

**Comment by mikeoliphant** [comment]
The output clipping was indeed a bug - it has been fixed in the code, and should be in the next release of the plugin.

See here:

https://github.com/sdatkinson/NeuralAmpModelerPlugin/commit/6432f52f6473cf57c80d15ccc25f4b95c738c64d
