### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CameronYoung098** [sdatkinson/NeuralAmpModelerPlugin#146]
there are no instructions for installation so I mostly winged it however I used the installer as usual then placed the extracted plug in folder into the plug in folder of Pro tools on my windows computer and yet I cant seem to find the plug in anywhere. any thoughts on where the issue may come from?

**Comment by sdatkinson** [comment]
Can you provide better details about what you're doing? I can't tell what steps you took, what kind of computer you're using, what DAW you're expecting to work.

The Bug template asks for the information that should help me understand what's going wrong. If you can submit a bug filling out that information, I may be able to help better.

Thanks!

**Comment by sdatkinson** [comment]
Thanks! This is very helpful.

> 5. I then copied the plug in folder titled NeuralAmplugin-0.7.1 into
This PC < OS(C:) < Program Files < Common Files < Avid < Audio < Plug-Ins
> 6. From now I presumed the plug in would appear in Pro Tools like other
plug ins have done in the past however it doesn’t seem to have appeared in
any of the categories of plug ins.

I see. The Windows installer provides the options to install a standalone application and a VST3 plugin. I believe that the default installation location for the VST3 plugin is C:\Program Files\Common Files\VST3.

Since you're using Pro Tools, don't you need an AAX plugin? AAX isn't currently supported, but it's got a feature request; see #74.

If there is a way for your DAW to use VST3 plugins, you should be able to use it by making sure that your DAW scans the path I wrote above.

Let me know if that answers your questions.

**Comment by KvlaMusic** [comment]
Hi Steven, thanks for making this incredible Amp Modeller. 

But I have an issue with the VST3 version, currently, I used Cakewalk DAW. So, I can open it in DAW, loading it with the AMP and IR models, but if I try to move the plugin position on the channel effect shelf or load another NAM VST3, the plugin "crash" ... like bypass-ing itself with the output bar stuck at the top end. Is there a way I can fix it?

Cheers!

**Comment by sdatkinson** [comment]
Closing this issue since I haven't heard back from OP.

@KvlaMusic, it sounds like you're having a different problem. Would you please search for "Cakewalk" and see if there are any other Issues that match what you're experiencing? If not, then please make a new Issue and provide the details in the template so I can help.

Thanks!

**Comment by KvlaMusic** [comment]
Hi @sdatkinson, it turns out, i have the same issue like #102. I'll turn my attention there.

Thanks!
