### ISSUE TITLE
[Improvement/Doubt] Use of C++ Neural Network Libraries

### ISSUE THREAD

**Issue by dbanshee** [sdatkinson/NeuralAmpModelerPlugin#159]
Taking a look at the code, in particular the DSP library, I see that the execution on C++  of the neural network developed in pythorch (neural-amp-modeler project) is re-implemented here by hand.

Is there a reason why PyTorch C++ API or OpenNN or some similar library is not used?

It's just a doubt. Excellent job anyway.

**Comment by sdatkinson** [comment]
Good question.

The answer is ultimately because of the convolutions.

For things like an LSTM, one could do it, no problem.

The problem is that:
1. a ConvNet, to predict a single output, has to look back a long ways.
2. However, _all of the results of the previous convolutions will be the same, so it's wasteful to compute them again and again._

This isn't a problem in traditional ML applications (like the training set up)--one can process large batches of audio all at once, and make use of these "repeated intermediate values within a single forward pass, and the additional overhead due to processing different chunks independently is minimal. But, it's not tenable in real-time audio, where the buffer is ~1% of the receptive field--you'd be "wasting" 99% of the computation if you used a stock convolution op.

The dsp library solves this by caching the previous convolution outputs, given that the next convolution ops are going to be on the immediately-following samples. The result is a critical ~100x speedup that makes this possible.

I'm not aware of e.g. LibTorch having (stateful!) ops that match this need. But if they do, then perhaps it could work.

**Comment by dbanshee** [comment]
Thank you very much for satisfying my infinite curiosity. :D

A good and clever optimization.
I guess it will be worth it in the results and the extra effort just for using convnet (I haven't had time to really analyze with my ear the differences between different networks for the same input yet).

On the other hand I suppose that it is possible to make use of GPU acceleration in this implementation.

Are you studying as an option an implementation of the DSP library through CUDA or similar?
I think pytorch uses HW acceleration on Apple M1 (skipping the problem of using covnet).

I don't know if it's worth thinking about the type of hardware of the user profile of this software.

**Comment by sdatkinson** [comment]
I'm not personally looking into using the GPU for real-time audio.

I've rolled CUDA kernels for non-RT code before and know the challenge...not really something I could probably hope to succeed with, given how little the chunks of time are I can spend focusing on this.
