### ISSUE TITLE
[Feature] "Lite" version of plugin

### ISSUE THREAD

**Issue by rossbalch** [sdatkinson/NeuralAmpModelerPlugin#160]
I realise the ship may have sailed at this point, but I would love a parellel release of a light version of the plugin that is a NAM loader plus input and output only. I'm sure quite a lot of us use the plugin version this way due to the array of available options in the DAW.

**Comment by sdatkinson** [comment]
No, this may be doable...do you remember the "cassette" version? 😄

The first way that comes to mind is by `#define`ing a flag so that it builds either as the "basic" or "full" version.

Perhaps a second project for a different plugin may also be the right thing to do, but I'm not sure. Feels like it needs thought. No doubt there'd be a lot of code I'd want to re-use.

**Comment by sdatkinson** [comment]
Coming back to this, I think that I'm going to be focusing on supporting one version of this plugin. As of now, it's going to be the current version.

If a re-design come into view at some point, I'd be happy to think of this at the same time 🙂
