### ISSUE TITLE
[BUG] Serializing a path to the model/ir is error prone

### ISSUE THREAD

**Issue by olilarkin** [sdatkinson/NeuralAmpModelerPlugin#163]
Users will want to recall their projects using NAM sounds, but the IR and model may no longer exist at the locations stored in the plugin state. It would be better to serialize the model and the IR imo, since it's not that much data to add to a DAW project file

**Comment by sdatkinson** [comment]
Fair point. Will this require me to define a new serialization format, or is there something in iPlug2 that can help with serialization/deserialization of complex data?

Come to think of it, I think i recall that nlohmann::json defines a method for instantiating a JSON from a raw string...perhaps there's a "to string" and this could be used to serialize & deserialize as a `WDL_String`?

**Comment by damiangr** [comment]
> Fair point. Will this require me to define a new serialization format, or is there something in iPlug2 that can help with serialization/deserialization of complex data?
> 
> Come to think of it, I think i recall that nlohmann::json defines a method for instantiating a JSON from a raw string...perhaps there's a "to string" and this could be used to serialize & deserialize as a `WDL_String`?

You can use Base64 encoding to string. I don't know Iplug2 API but JUCE has this function  implemented.

**Comment by pawelKapl** [comment]
Hey @sdatkinson @olilarkin ! So i created this two PR drafts's ☝️  as my modest attempt to solve this issue. I am not 100% happy with this solution, but it seem to work. The problem lies in the boundaries of Core library and plugin contexts - core library is responsible of loading models from files. Imo it shouldn't be - this way we don't have a control over loaded models in plugin.

Anyway i am open for every suggestions, tweaks etc. If u will like this implementation i will proceed with further testing and beautifying code a little bit.

**Comment by sdatkinson** [comment]
Update: I don't think that I'll be pursuing this change because it's not consistent with how other programs that depend on other files tend to behave (e.g. a DAW project doesn't serialize the audio files it uses, nor do IR loaders like NadIR). Instead, I can create a popup if the file isn't found on re-load.
