### ISSUE TITLE
Hard clipping outputs seems strange

### ISSUE THREAD

**Issue by olilarkin** [sdatkinson/NeuralAmpModelerPlugin#164]
I was a bit surprised to see this... are you sure about doing that?

https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/f661249db20aba8be8189fdc87eefdb3f34f3dc2/NeuralAmpModeler/NeuralAmpModeler.cpp#L876

**Comment by sdatkinson** [comment]
Good question. I'll throw it back to you since I sincerely don't know: Is it valid for a plugin to output values beyond [-1,1]?

I had assumed not since the output of the plugin might go to the output of the DAW, which obviously can't bounce anythign out of range...but since you're asking, I presume I'm mistaken and this is something that people do?

**Comment by olilarkin** [comment]
Yes it's valid. For the standalone APP you might want to prevent sending a value to the DAC that is greater than +/- 1. Inside the DAW it's just going to mean your signal goes into the red and needs gain reduction afterwards.

**Comment by sdatkinson** [comment]
Good to know! I'll grab it then.

**Comment by sdatkinson** [comment]
I assume an `#ifdef APP_API` would do the trick?
