### ISSUE TITLE
[FEATURE] When saving a daw project which uses NAM - save used nam file in project.

### ISSUE THREAD

**Issue by dmt-hub** [sdatkinson/NeuralAmpModelerPlugin#165]
**Is your feature request related to a problem? Please describe.**
Lets say you change computers and want to open a project which uses nam, auto-saving the used nam files into project so it never gets lost.

**Describe the solution you'd like**
Save .nam files into project.

**Comment by sdatkinson** [comment]
Sounds like #163?

**Comment by damiangr** [comment]
This is a good idea as original NAM or IR file may be moved or deleted. I would aproach this in this way:
- encode nam file with Base64 and store it to namdata variable as string
- encode IR file with Base64 and store it to IRdata variable as string
- store both variables when DAW saves the session 
- load both variables when DAW load the session
- decode Base64 ir and nam string back to data and initialise nam with it 
- optional  right click on nam or ir window will bring option to export stored ir or nam to file

**Comment by sdatkinson** [comment]
Having thought about this for a while, I think I'm going to not pursue this. The main reason is because it's not consistent with how other things work.

For example, if I've got a DAW project, and an audio file that it uses is misplaced, then there'll be an error the next time I attempt to open the project and I'll be told to find the file.

This also seems to be how NadIR works (tested with v1.0.2 x64).

I'm open to making there be an error modal in a similar way, so I think the way forward is I'll implement #293.
