### ISSUE TITLE
[FEATURE] Consider license change

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/NeuralAmpModelerPlugin#174]
Thoughts on changing the license for the plugin to GPL?

I think it is important that the core NAM code be under a liberal license like MIT, but using GPL for the plugin would have a few potential benefits:

- allows us to use GPL licensed 3rd-party code
- encourages 3rd-party improvements to be shared back
- reduces the possibility of low-effort clones causing confusion

**Comment by bananu7** [comment]
As both a user and a developer I am strongly against this.

**Comment by mikeoliphant** [comment]
> As both a user and a developer I am strongly against this.

Care to say why?

**Comment by James-F2** [comment]
Nay for GPL.
I would like to see NAM in commercial hardware one day, it has to spread far and wide.

**Comment by mikeoliphant** [comment]
Just to be clear - this proposal is for the **_*plugin*_** code, not the NAM code itself, which is in a different repo. As I said, I think MIT is the correct license there.

I would love to see hardware manufacturers using NAM. They would have no interest in this plugin codebase, though. I have a hard time seeing where a closed-source, 3rd party fork of the *plugin* would be useful to the NAM community.

As an example of my first point above, I've considered adding resampling to the plugin to allow it to work properly at DAW rates other than 48k. One of the options I would usually consider for this is (zita resampler)[https://kokkinizita.linuxaudio.org/linuxaudio/zita-resampler/resampler.html]. But we can't use it because of our license.

**Comment by sdatkinson** [comment]
@mikeoliphant, this makes sense to me.

Let me have a look through the various licenses and see what I think in this context.

**Comment by colin-campbell** [comment]
I'm also a user and developer. Strongly +1 for GPLv3. @James-F2 GPL is used in commercial products every second of every day - they just rightly need to release the source to their modifications of the original code. And so they bloody well should. Parasites living off the hard work of the original developer and the rest of the community that builds upon the creative work is bloody criminal. 
Especially in this proprietary and predatory audio market of vendor lock-in, ilok nonsense and rent-seeking.

**Comment by olilarkin** [comment]
@mikeoliphant iPlug2 has an over/undersampler based on HIIR (DWTFUWPL) in the codebase already, which would be suitable.

GPL'ing the plug-in seems strange to me since the original IP is the DSP part and that is what competitors would want to use.

**Comment by olilarkin** [comment]
regarding point 1, why would this repo being GPL allow the use of GPL code? Also wouldn't it prevent an iOS appstore release? https://developer.apple.com/forums/thread/18922

**Comment by bananu7** [comment]
> regarding point 1, why would this repo being GPL allow the use of GPL code?

GPL is a licence designed to coerce people into using it. The idea is that if you make your code GPL, you can then use other GPL code.

@mikeoliphant to answer your question - but this is the last post I want to make it here. I don't want to turn this thread into an opinion war; I'm only answering because I felt compelled to produce some arguments, but this is by far not an exhausted position on why to not use GPL.

If "MIT for libraries, GPL for apps" made any sense, this provision wouldn't be necessary. By definition, if anyone feels the need to reuse parts of code from another _app_ (client, UI, whatever), those parts should then be relicensed as MIT, because they're effectively becoming libraries. This introduces a pointless (to me) distinction.

While I'm all for OS creators profiting for their work in lieu of corporations stealing their work, I simply disagree that GPL is a good solution for this, especially considering funding issues of GPL software.

**Comment by mikeoliphant** [comment]
> I, as an open source creator, have been forced to look for alternatives to GPL dependencies

As have I, but only in situations when I wanted to use someone else's code without sharing my own - so I respected their decision about how they wanted to share their code.

In my experience, people are rarely convinced one way or another in discussions about the GPL, so I'll refrain from further comment. If it were my repo, I would make it GPL. Since I am only a contributor - that isn't my decision. I will be happy to continue contributing either way.
