### ISSUE TITLE
[FEATURE] - plugin connects to tonehunt.org

### ISSUE THREAD

**Issue by offthesky** [sdatkinson/NeuralAmpModelerPlugin#191]
tonehunt.org is an amazing site for this nam plugin!  if somehow the plugin was able to access it's api, allowing you to browse and even download .nam files(perhaps built into, if any, future .nam browser?), would be amazing! i realize this is a crazy, probably too-big idea, but its fun to dream :]

**Comment by sdatkinson** [comment]
Sounds cool! But also something that's a bit more to take on than I have eyes for personally at the moment.

My sense is that it would also add quite a bit of complexity to the plugin, so my first-order answer is going to be "no", with the subtext that if someone can pitch this in a way that's sufficiently modular to the existing code (so that it could be easily "feature flagged" in and out, b then that would be key to lessening the risk. I don't want to get this in, have it be buggy or clumsy, and be saddled with needing to baby it.

If someone wanted to take it on, it'd be a great show of confidence if they could start by organizing some of the controls code and making it more idiomatic with the iPlug2 framework... Basically demonstrate to me that you know your way around the code and are giving high-quality contributions.

This^ is something I've been on the learning curve with in general with this, maintaining a project with a lot of interest and trying to balance being inclusive with stewarding the project. So since this is a rather big feature, I figure it's a good exemplar to kind of map out how these might get worked on.

**Comment by IzuTJ** [comment]
Perhaps just mentioning them in the readme is a great start.
Here is a link to their github:
https://github.com/scottcorgan/tonehunt

**Comment by sdatkinson** [comment]
Closing this because it's linked on https://neuralampmodeler.com
