### ISSUE TITLE
[FEATURE] Ship .vst3 plugin as well as installer

### ISSUE THREAD

**Issue by glenclayton** [sdatkinson/NeuralAmpModelerPlugin#211]
Since you must already build it can you also include the .vst3 file in the release zip so we can copy it directly rather than have to use the installer exe ?

**Comment by dr-chase-g3ka1** [comment]
I like this idea.

**Comment by sdatkinson** [comment]
Can you help me understand why you'd want this?

A workaround right now would be to build from source; does that work for you?

**Comment by dr-chase-g3ka1** [comment]
@sdatkinson 
First of all, thank you for your hard work. NAM works and it's amazing. 
This issue would be convenience improvement, because different apps lookup different paths for VST-s and sometimes people have to copy from the install destination.
Also not everyone needs the stand alone app, only the VST.
An easier work around is to install and copy from VST destination.
Some people are afraid to run exe files because it's always a security risk. 
An ideal solution would be to create a zip distributable near the installer exe file. I am not sure how difficult would it be.

**Comment by glenclayton** [comment]
I can take a look into implementing this if @sdatkinson is supportive. There are 2 options - either include the .vst3 file in the current zip package, or create a separate one just for it.

**Comment by sdatkinson** [comment]
> This issue would be convenience improvement, because different apps lookup different paths for VST-s and sometimes people have to copy from the install destination.

It seems to me like specifying the install location would be preferable and more in line with what I usually see? If this isn't part of it right now (I don't remember), then opening an Issue regarding it would be fine.

> Also not everyone needs the stand alone app, only the VST.

The installer currently allows you to select which parts to install, so I think this part is ok.

> Some people are afraid to run exe files because it's always a security risk.

That doesn't seem like a good reason--executable installers are the norm, and I'm happy to stick with it. It does sound reasonable, though to ask for signed installers so that Windows & Mac will stop shouting so much 😉 This is tracked in #185.

> An ideal solution would be to create a zip distributable near the installer exe file. I am not sure how difficult would it be.

I'm actually not really keen to add artifacts to the releases--there has been confusion in the past when users saw more than one thing that looked like it might be the right thing to download. Given that lesson, I'd like to keep it to one artifact per OS.

---

Since I think that the points in this issue are either resolved or would be better tracked in a narrower-scoped issue, I'm closing this.
