### ISSUE TITLE
Mac Osx 10.13.6 Mojave Please!!!

### ISSUE THREAD

**Issue by Vladzibor** [sdatkinson/NeuralAmpModelerPlugin#239]
**Thanks for taking the time to write a feature request!** Use the following prompts to help you describe what you're looking for.  The more info you provide, the easier it'll be for me to understand what I can do to make it happen for you without having to come back and ask you questions.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Vladzibor** [comment]
Sorry - only macOS 10.15 (Catalina)  MAC OSX 10.13.6 Mojave Please!!!!! :-)

**Comment by sdatkinson** [comment]
#23

**Comment by Vladzibor** [comment]
Oh, what a pity that the plugin does not work in MOJAVE 10.13.6 Millions of users still work in this operating system. Especially in such difficult times.

**Comment by DeadPixel72** [comment]
Yes.. it would be amazing to have Mojave compatibility... I've been using NAM since the beginning of the year, and... simply put, I am so impressed, my Kemper, etc.. is history.. and I am using NAM for ALL my guitar amp "tone", and ofc pairing with my favorite time based effects and so on.  Long story short, myself, and many others I know.. have to use a two machine (computer) workflow, due to other plugins we refuse to give up..  whilst also refusing to use any other "amp" plugin other than NAM..
