### ISSUE TITLE
[BUG] 0.7.4 RC - Drop down list issue

### ISSUE THREAD

**Issue by James-F2** [sdatkinson/NeuralAmpModelerPlugin#291]
The new drop down menu has created an issue where you have a lot of files in one folder and you can't select specific file, the drop down list takes the entire height of the monitor and scrolling with the small arrow takes ages.

This bundle has 190 files and scrolling to the bottom of the drop down list is pain.
https://tonehunt.org/ArlingtonAudio/cc417d46-d6d0-4a9b-8142-506964981b2c

Since there is no way to choose a single file, browsing a folder with many captures became a chore, mouse-wheel isn't working either to scroll faster down the list.

![scrolling](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/31185814/0288a057-09f9-48e5-a44e-54cc19ce9799)

@sdatkinson 

A good solution would be to open a file not a folder and also remember the position of the drop down scroll list.

**Comment by sdatkinson** [comment]
Gotcha. I hadn't had a chance to try this in Windows (Mac scrolls fine).

The reason why I switched it to picking folders was because if you pick a single file on the Mac standalone, the arrows don't work because the plugin doesn't have permission for the rest of the folder (only exception is if you happen to be storing your files in `Music/`, currently.... which I imagine many people might not)

What I may be able to do is select file for everyone _except_ Mac standalone, who can scroll, fortunately.

**Comment by James-F2** [comment]
It does scroll in Windows, just very slow.
You can imagine people holding the little arrow for 2 minutes to reach capture 225.

**Comment by olilarkin** [comment]
On windows you can enable multiple columns on the popup menu which can help displaying massive lists via IPopupMenu::SetNItemsPerColumn(). That might alleviate this problem.

Still, I preferred the ability to select an individual .nam via the regular OS dialogs

**Comment by James-F2** [comment]
> on Windows the keyboard down and up arrow keys work for scrolling (much faster), and also alphabetic letters work too.

Thanks for the tip, very useful, it also wraps around.
It would be nice though if the drop down list showed the current selection instead starting from the top, also if PageUP/Down and Home/End worked.
