### ISSUE TITLE
Naming a model with 'nam_' at beginning of name, fails to load [BUG]

### ISSUE THREAD

**Issue by DomMcsweeney** [sdatkinson/NeuralAmpModelerPlugin#306]
Naming a model with 'nam_' at beginning of name, fails to load in NAM. 
Naming it 'mom_' is fine. 
(She is).  
![image](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/86134812/2fcaa189-0904-484e-bddd-3a3e4e6cf9f2)

Also, a double '.nam' at the end of the file name causes issues too. 

Here's an example of both issues: 

![image](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/86134812/54ccd6d4-41f8-429c-94aa-e2a4c4e0a081)

**Comment by sdatkinson** [comment]
It _seems_ like any name with "nam" in it is affected?

![image](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/393a5c27-2b1c-40c1-8a4e-4ad759dd2370)

**Comment by sdatkinson** [comment]
Replicated over here:

<img width="967" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/6501babe-a732-443a-bdd9-0c4bf7a11fca">

**Comment by sdatkinson** [comment]
The root cause is the use of `strstr` in `IDirBrowseControlBase::ScanDirectory()`, which is used to check the extension of a given file against the expected extension.

`strstr` finds the _first_ occurrence of `"nam"`, so for `strstr("birdie nam.nam", "nam")` we get a pointer to `"nam.nam"`, which doesn't match the expected file extension, and the file isn't logged in the list of files to be iterated on.

See:

<img width="724" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/3bac8db6-0843-4826-91e7-2fea304567dc">

So this is an iPlug2 issue. I'll open an Issue over there and once the fix is pushed we can pull it in over here and fix our Issue 🙂

**Comment by sdatkinson** [comment]
Cut an Issue: https://github.com/iPlug2/iPlug2/issues/989
Published PR: https://github.com/iPlug2/iPlug2/pull/990

Once that PR goes through, I'll need some help from @olilarkin on updating the branch that we're tracking over here (...which is it? 😅)
