### ISSUE TITLE
Can't load files with non-ASCII characters in path

### ISSUE THREAD

**Issue by rafadomper** [sdatkinson/NeuralAmpModelerPlugin#307]
Hi dear,

I've just installed nam 0.7.4 on my win 11 and couldn't use it properly either as plugin in Reaper either as a stand-alone version. I can open it, it's ok. But when I go browse the files, it simply doesn't apply the preset file in the first field or the IR file in the second one. It doesn't give any error as well.

**Comment by golentones** [comment]
Same issue here.  For example, the files in the "Marshall JCM 800 (Daniel Heß + Jon Arnold).zip" do not load at all.  For some others that also did not load, editing and changing the file name fixed it.  For this one, it doesn't.

**Comment by sdatkinson** [comment]
> Same issue here. For example, the files in the "Marshall JCM 800 (Daniel Heß + Jon Arnold).zip" do not load at all. For some others that also did not load, editing and changing the file name fixed it. For this one, it doesn't.

This is a helpful hint.

@rafadomper @golentones , I wonder if this is a redux of the unicode issues that were resolved previously.

If you change the model location and name sure that there are *no non-ASCII characters in the file path*, does it work?

**Comment by golentones** [comment]
Yes! That was it!  Had to remove the "ß" in the folder name.  Thank you!

**Comment by sdatkinson** [comment]
Good to know--we've got  workaround and the path to fixing this is a lot clearer now.

Thanks!

**Comment by golentones** [comment]
My pleasure!  Thank you!

**Comment by sdatkinson** [comment]
Related Issue: #116 
PR was: #201

**Comment by rafadomper** [comment]
> > Same issue here. For example, the files in the "Marshall JCM 800 (Daniel Heß + Jon Arnold).zip" do not load at all. For some others that also did not load, editing and changing the file name fixed it. For this one, it doesn't.
> 
> This is a helpful hint.
> 
> @rafadomper @golentones , I wonder if this is a redux of the unicode issues that were resolved previously.
> 
> If you change the model location and name sure that there are _no non-ASCII characters in the file path_, does it work?

@sdatkinson Yes, I did it and it worked! Dear, thanks a lot!

**Comment by sdatkinson** [comment]
Interestingly, I can replicate this on Win11, but _not_ on macOS!

**Comment by sdatkinson** [comment]
Root cause appears to be the use of [`GetOpenFileNameW` in `IGraphicsWin.cpp`](https://github.com/iPlug2/iPlug2/blob/b3a51573f45c830755ee4426d2d1eb04cf645359/IGraphics/Platforms/IGraphicsWin.cpp#L1660), which [Google tells me](https://learn.microsoft.com/en-us/windows/win32/api/commdlg/nf-commdlg-getopenfilenamew) is discouraged to be used in favor of the [Common Item Dialog](https://learn.microsoft.com/en-us/windows/win32/shell/common-file-dialog).

I'll admit this is a bit "far from home" for me, but it seems to me after digging this deep that there's an issue here that needs to be solved in iPlug2; after that gets fixed, we'll be able to grab it over here and I suspect all will be well 🙂

**Comment by sdatkinson** [comment]
Issue cut ☝🏻
