### ISSUE TITLE
[?] Tone stack ranges

### ISSUE THREAD

**Issue by olilarkin** [sdatkinson/NeuralAmpModelerPlugin#342]
The Bass, Middle, and Treble controls currently have a range of 0-10, and default to 5 for the user. Then they are converted to dBs like this... 

```
    const double bassGainDB = 4.0 * (GetParam(kToneBass)->Value() - 5.0); // +/- 20
    const double midGainDB = 3.0 * (GetParam(kToneMid)->Value() - 5.0); // +/- 15
    const double trebleGainDB = 2.0 * (GetParam(kToneTreble)->Value() - 5.0); // +/- 10
```
 
 Are these units consistent with guitar amps? it seems slightly strange to me to show a value of 5 when there should be no gain adjustment to that band.

**Comment by James-F2** [comment]
> Are these units consistent with guitar amps?

No, the eq is not a guitar tonestack, it is a standard shelving for Bass and Treble, and peaking for Middle.
I also think -10, 0, +10 will make more sense since the eq is active.
Another thing to consider is the a knob with a graphic that is half full blue line at 5 which is actually 0.

BTW, ToneX allows the user to change the center frequencies of the eq, that is very useful.
![ToneX eq](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/31185814/02709db4-3d22-4ece-8132-e9ee03ff260f)

**Comment by sdatkinson** [comment]
Right, "5" is usually what guitar amps show at noon.

Eg: https://images.app.goo.gl/Sufr4oVppG9qS8So8
