### ISSUE TITLE
[FEATURE] Metadata tags and images

### ISSUE THREAD

**Issue by RustoMCSpit** [sdatkinson/NeuralAmpModelerPlugin#343]
E,g, 
Clean tone tag for example in the metadata so I can sort while in the app

**Comment by sdatkinson** [comment]
This would probably be pretty nontrivial to do, the way file browsing is implemented. Given the open-source nature of this project, I'm keen to set the bounds of scope a bit tighter than implementing this because of the other pieces that it'd bring in (e.g. the UI for applying such filters). This is asking to bite off a bit more than I can maintain, I think.
