### ISSUE TITLE
[BUG] Can't select model (NAM 0.7.5 Logic 10.7.9)

### ISSUE THREAD

**Issue by inglar** [sdatkinson/NeuralAmpModelerPlugin#367]
**Describe the bug**
After moving folder with .nam models "Select model..." doesn't work.

**To Reproduce**
1. Add to project NAM plugin, select model from .nam models folder
2. Save project. Exit.
3. Move .nam models folder to other location.
4. Open project, open plugin and try to select another model.
5. It does nothing when clicking Open after selecting .nam file

**Expected behavior**
"Select model..." should work nevertheless plugin could find selected model or not.

**Screenshots**
Video: https://drive.google.com/file/d/1IwvWsjnS9sVwi_cFq5Q16O8iTPCwvwy4/view?usp=drive_link

**Desktop (please complete the following information):**
 - OS macOS Ventura 13.5.1
 - Plugin version 0.7.5
 - AU
 - DAW Logic Pro 10.7.9

**Additional context**

**Comment by sdatkinson** [comment]
I can't access the video you shared.

Based on your written description, this bug is reported already here: #293.

A fix was merged in #359 that will note that loading failed on step (4) of your process above. It'll be in next release.

If you want to, you can build from source and confirm that the latest commit does what you expect. If it doesn't feel free to re-open the Issue.
