### ISSUE TITLE
[BUG] Can't build - ModuleNotFoundError: No module named 'parse_config'

### ISSUE THREAD

**Issue by jonahclarsen** [sdatkinson/NeuralAmpModelerPlugin#380]
I cloned the repo and opened NeuralAmpModeler-macOS.xcodeproj in Xcode 14.3.1 (MacOS 14.0, M2). When I try to build, I get the following error:
```
Traceback (most recent call last):
  File "/_Plugins/NeuralAmpModelerPlugin/NeuralAmpModeler/projects/../scripts/update_version-mac.py", line 19, in <module>
    from parse_config import parse_config, parse_xcconfig
ModuleNotFoundError: No module named 'parse_config'
Command PhaseScriptExecution failed with a nonzero exit code
```

I'm sure I'm missing something. I tried creating a new conda environment and ``pip install``ing https://github.com/sdatkinson/neural-amp-modeler, which seemed to install dozens of packages, but when I run ``update_version-mac.py`` from that env I get the same error.

**Comment by sdatkinson** [comment]
You don't need the trainer to build this--all of the dependencies are self-contained.

I think the issue is that you didn't properly clone the submodules used by this repo.

In short, clone with `git clone --recurse-submodules [path]`.

Look up git submodules if you're unfamiliar with them.

Let me know if that works.

**Comment by sdatkinson** [comment]
Haven't heard back; closing since I assume this did it
