### ISSUE TITLE
[BUG] Plugin can't be validated in Logic Pro X

### ISSUE THREAD

**Issue by anonymousguy96** [sdatkinson/NeuralAmpModelerPlugin#402]
Hi.
I've just installed Nam but can't enable it in Logic Pro.
I've tried to rescan the plugin numerous times and reinstalled it twice, but nothing seems to work.

Can you help me out?
I'm gonna drop some useful info for you.
Have a great day, and I'm sorry for the inconvenience.

Hackintosh Laptop:
MacBook Pro (Retina, 13-inch, Late 2013)
macOS Mojave version 10.14.6

Daw: Logic Pro v10 .5.1

Report:

validating Audio Unit NeuralAmpModeler by Steven Atkinson:

    AU Validation Tool
    Version: 1.6.1a1 
    Copyright 2003-2013, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aufx' - '1YEo' - 'SDAa'
--------------------------------------------------
Manufacturer String: Steven Atkinson
AudioUnit Name: NeuralAmpModeler
Component Version: 0.7.5 (0x705)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF

validation result: couldn’t be opened

**Comment by sdatkinson** [comment]
Thanks for the info.

My guess is that the core problem (or at least sufficient for this not to work for you) is the fact you're on Mojave. There's at least one issue preventing this plugin from running on earlier than 10.15 (#23).

If you're able to test on a version of macOS that meets that spec and still have some other issue, then we can look into that. But, I think that what you're seeing is either exactly related to #23 or at least can't be meaningfully helped otherwise.

Let me know what you want to do next; if we can't try this without fixing that issue, then I think I'll have to close this as a duplicate.

**Comment by sdatkinson** [comment]
Ok. Thanks for letting me know.

I don't think there's anything I can do for this at the moment then, unfortunately.

**Comment by anonymousguy96** [comment]
Ok, thank you
