### ISSUE TITLE
96K version [FEATURE]

### ISSUE THREAD

**Issue by laurencebush** [sdatkinson/NeuralAmpModelerPlugin#462]
I'm always frustrated when I'm working in 96K and it resamples my captures down to 48K. I would capture everything again at 96K, as aliasing issues are much lower at this sample rate.

A 96K version of the plugin would be great, but even better would be the ability to state which sample rate you are working at in the plugin. Even better still would be the option to have a separate nam model loader for offline renders at a higher sample rate to get rid of even further aliasing.

The alternative, which isn't really a real alternative, is MGuitarArchitect, which allows you to oversample. This however pulls the frequency response of the model up and octave the further you go.

It's really important to do this because of aliasing issues.

**Comment by sdatkinson** [comment]
This plugin already plays models that run at any sample rate ; the trouble is the models you're using.

The models need to run at the sample rate of the data they were trained on. If you want a model that runs at 96k, you need to train the model on 96k data. This is already supported by [the trainer](https://github.com/sdatkinson/neural-amp-modeler), but you need to use the full-featured CLI trainer since the standardized trainer needs to use a [standardized input](https://drive.google.com/file/d/1Pgf8PdE0rKB1TD4TRPKbpNo1ByR3IOm9/view?usp=drive_link), which is 48k.

Hope that helps.

**Comment by laurencebush** [comment]
That's great! I've made a 96k version of the 3.0.0 version, which I had to generate the tones again and add some saturation to get some more harmonics. Plus some 48 kHz sweeps downwards to make sure I'm not missing anything.
