### ISSUE TITLE
[FEATURE] iplug now supports targeting .clap so can you release a .clap format

### ISSUE THREAD

**Issue by RustoMCSpit** [sdatkinson/NeuralAmpModelerPlugin#483]

**Comment by sdatkinson** [comment]
What's the benefit of doing so?

**Comment by RustoMCSpit** [comment]
> What's the benefit of doing so?

some daws only take .clap, .clap also has automation benefits and is more optimisied than vst3 (and it's mit too)

**Comment by sdatkinson** [comment]
Which DAWs only support CLAP? (I'm a pretty "mainstream" DAW person--I use REAPER mostly now, and used to use Cubase.) I don't think I've ever seen someone say they can't use NAM because their DAW doesn't support the plug-in types that this repo builds.

Honestly, with all of the products out that now implement NAM, I'm probably keen to _reduce_ what this plug-in does, not expand it. So if I could e.g. drop AU or VST3 support because everyone could use CLAP instead, then that'd be fine. But if not (and someone else's plug-in is available as CLAP--do you know anyone who's done this?), then I'm somewhat keen just direct folks over to that other plug-in instead.

**Comment by RustoMCSpit** [comment]
> So if I could e.g. drop AU or VST3 support because everyone could use CLAP instead, then that'd be fine. But if not (and someone else's plug-in is available as CLAP--do you know anyone who's done this?), then I'm somewhat keen just direct folks over to that other plug-in instead.

most DAWs have clap support but ableton is still yet to adopt. FL, reaper, bitwig, etc. all have clap.

https://cleveraudio.org/1-feature-overview/

**Comment by RustoMCSpit** [comment]
> About

> This is a cleaned up version of [the original iPlug2-based NAM plugin](https://github.com/sdatkinson/iPlug2) with some refactoring to adopt better practices recommended by the developers of iPlug2. (Thanks [Oli](https://github.com/olilarkin) for your generous suggestions!)

> *could also support VST2, AAX, CLAP, Linux, iOS soon.


shouldnt you get rid of VST2 from the about?

**Comment by sdatkinson** [comment]
True :)

**Comment by RustoMCSpit** [comment]
also about the linux, any progress? if you export clap and accomplish linux i can add this here https://github.com/RustoMCSpit/awesome-linux-clap-list

**Comment by olilarkin** [comment]
More formats = more maintenance work. 

Indeed iPlug2 supports CLAP now. iPlug2 Linux support is far off though.

@RustoMCSpit this kind of "issue" on open source projects is not so helpful in my opinion... it's a feature request that is demanding a whole lot of work from the maintainers... for free.

**Comment by RustoMCSpit** [comment]
> this kind of "issue" on open source projects is not so helpful in my opinion... it's a feature request that is demanding a whole lot of work from the maintainers... for free.

it's a suggestion, i dont demand anything. thank you for all you do.

> iPlug2 Linux support is far off though.

id guess 2026-ish, regardless if you were to pick between clap and vst3 clap makes more sense in the long run given its nicer license and rapid adoption

**Comment by sdatkinson** [comment]
FWIW it _is_ just a feature request.

To make a decision here, let's say that for now this won't be on my radar for this plug-in. I had a look and there's some cool stuff going on with CLAP for sure, but since I need to prioritize my time this one will be below the line for now. But I'll keep it in my if I do some other project that woudl benefit from a fresh take and plug-in standard.

Closing.

**Comment by olilarkin** [comment]
True - it's just the OP has been a bit demanding elsewhere on github for things. Different people use github differently. For massive feature requests like "please make a clap version", "please add linux support" I find forums/discords a more appropriate place to discuss it with the maintainers first, especially if you are not a dev yourself, otherwise I tend to just close the request as you have done here. my 2c

**Comment by RustoMCSpit** [comment]
> True - it's just the OP has been a bit demanding elsewhere on github for things. Different people use github differently. For massive feature requests like "please make a clap version", "please add linux support" I find forums/discords a more appropriate place to discuss it with the maintainers first, especially if you are not a dev yourself, otherwise I tend to just close the request as you have done here. my 2c

fair nuff and sorry about the iplug2 thing 🙏
