### ISSUE TITLE
[BUG] Cannot install 0.7.10 on macOS Sequoia. Security warning.

### ISSUE THREAD

**Issue by lxne** [sdatkinson/NeuralAmpModelerPlugin#503]
**Describe the bug**
0.7.9 is running fine, but I cannot install 0.7.10 on macOS Sequoia.
A security warning won't let it install.

**To Reproduce**
1. Try to install on a mac with macOS Sequoia
2. You'll get a security warning and it won't install.

**Screenshots**
<img width="409" alt="Bildschirmfoto 2024-09-22 um 00 12 31" src="https://github.com/user-attachments/assets/7b34dd4e-c65a-420b-8f10-02c5c6889d4f">

**Desktop (please complete the following information):**
 - macOS Sequoia
 - Plugin version 0.7.10

**Comment by sdatkinson** [comment]
I've replicated this.

Googling it, it seems that Apple has gotten peskier about unsigned packages with Sequoia (this isn't due to a change with NAM).

Here's a help article: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/15.0/mac/15.0

Following the directions allowed me to install. Let me know if it works for you too and I can call this resolved.

**Comment by lxne** [comment]
Thank you. That worked perfectly.
Sorry, could have worked that out myself.

Best wishes.

**Comment by sdatkinson** [comment]
All good. Nice to be aware of this and having solutions noted here is helpful 👍🏻
