### ISSUE TITLE
[BUG] Can´t uninstall NAM, when installed again it don´t open(Standalone)

### ISSUE THREAD

**Issue by Benji1308** [sdatkinson/NeuralAmpModelerPlugin#506]
Hello,

i didnt get a sound out of the NAM because i was figuring to trying out which input devices and output devices connect to my interface, it was a shame none of them worked, but my interface showed on the display (that´s also a problem) but i uninstalled it and wanted to install it again but sadly it wont pop up anymore on my screen and my happy feelings were gone, because i wanted to try the NAM so bad!!!!!!

Please Help QUICK!!!

Kind Regards and thank you in advance

**Comment by Petervos2018** [comment]
Maybe remove the settings.ini file from 

C:\Users\YOU\AppData\Local\NeuralAmpModeler 

and try to start again ?
(just trying to help)

**Comment by Benji1308** [comment]
Hello, thank you for your help, unfortunately it didnt work, any other recommendations?

**Comment by sdatkinson** [comment]
@Benji1308 have you had a chance to try @DomMcsweeney 's suggestions?

If those work then I'd like to close this as resolved. If not, it would really help with finding the solution if you took the time to fill out the bug report template thoroughly. Right now, I don't even know what operating system you're using (maybe Windows since it sounds like Peter's suggestion was something you were able to try?)

On Windows, typical places where NAM is installed are...
* C:\Program Files\Common Files\VST3\NeuralAmpModeler.vst3 (VST3 plugin)
* C:\Program Files\NeuralAmpModeler\NeuralAmpModeler_x64.exe (standalone)

...if you'd like to try removing them and re-installing.

**Comment by Benji1308** [comment]
hello steven,

yes! it worked perfectly fine for me!
thank you, you can close this as resolute.

kind regards!

Steven Atkinson ***@***.***> schrieb am Mi. 16. Okt. 2024 um
01:22:
