### ISSUE TITLE
[BUG] 0.7.12 may show some CPU increase relative to 0.7.11

### ISSUE THREAD

**Issue by vossenv** [sdatkinson/NeuralAmpModelerPlugin#545]
Possible small CPU increase in 0.7.12.  In my case, this is only a 10-12% increase (from 0.22% to 0.24/0.25% of total CPU).  I can't think of any reason to explain this, and users observe an increase in other DAWS as well:
https://www.facebook.com/groups/5669559883092788/?multi_permalinks=8786416471407098

## To reproduce
- Load up several instances of NAM for a better average view
- Make sure they all load the same NAM file
- Play a reamp  through them all at once
- Observe the CPU performance (I used reaper and the ctrl+p panel)

Repeat the above with 0.7.11

- I used the plugin installers to fully install each version
- Windows 11 / i913900k
- Focusrite Clarett @48k, 64 spls
- Reaper 7.27

Screenshots showing the difference for identical cases

0.7.11
![0711_4x](https://github.com/user-attachments/assets/156bef66-3e63-494a-9c56-68b66985a6f8)

0.7.12
![0712_4x](https://github.com/user-attachments/assets/52e744a9-e481-4fd1-bbb2-fb42ef285a78)

**Comment by vossenv** [comment]
Videos illustrating this


https://github.com/user-attachments/assets/b89c83b7-b6b3-4d5b-9e66-da1c99b51c66


https://github.com/user-attachments/assets/e24626ea-d421-4014-9e1b-b7c003651232

**Comment by sdatkinson** [comment]
Starting to check if I can reproduce this.

* Desktop (TODO specs): TODO result
* MacBook Pro (2020 13 inch Intel i5): TODO result
* MacBook Pro (2020 13 inch M1): Did not reproduce (0.39-0.41c, 0.39-0.41c)

**Comment by vossenv** [comment]
This also does not seem to reproduce on my M1 air

**Comment by sdatkinson** [comment]
Seems like a Windows-specific thing then, as far as we can tell?

**Comment by sdatkinson** [comment]
Ok.

* I was able to see a difference on my Windows desktop between 0.7.11 and 0.7.12
* On commit e2cd3b1 (current as of me writing this) I believe that we're back to normal. This makes sense I think--the root cause of the other issues people were having with 0.7.12 (e.g. #541) was this function call that keeps recursing on itself, which would conceivably consume compute as the host spends effort keeping it from doing silly things.

Can someone else verify that this fixes it?
