### ISSUE TITLE
NAM loads with some settings maxed out in Reaper[BUG]

### ISSUE THREAD

**Issue by Zappafile** [sdatkinson/NeuralAmpModelerPlugin#78]
Having set up NAM in reaper when I close a session and return the settings will "default" to max positions. Even the EQ which was not touched and is still in an off state will all be maxed out though still off.

I can reproduce this each and every time and even if I recall a saved preset FX chain in reaper the same issue persists. 

It would be great if the plug could hold any and all parameter settings within reaper. Not sure if this is a reaper thing or a NAM thing to be fair.

I am on a desktop running windows 11 and Reaper 6.75. This occurs with vst only not standalone. NAM 0.7.0

commit db4cf2dea019b1a8ef10b62cb2af6f5df2666608

I hope that helps.

**Additional context**
![NAM Recalled Reaper v6 75 Win11](https://user-images.githubusercontent.com/126454103/221511893-fc5ed5ce-907f-4d35-8939-50f8cc337842.jpg)

**Comment by sdatkinson** [comment]
Thanks! This is a NAM thing--the reason is that there are a different number of parameters in the plugin in the new version (thanks to the noise gate), so old saved plugins don't match up when loaded in.

Things should be ok if you start with a new version of the plugin. Is than an acceptable workaround?

**Comment by sdatkinson** [comment]
Got a few of these; going to close this and continue tracking on #81.
