### ISSUE TITLE
Popping sound

### ISSUE THREAD

**Issue by jaredbehrens** [sdatkinson/NeuralAmpModelerPlugin#9]
I receive a popping sound when I load a new capture. It happens every time even if I don't have the track record enabled.

I am using 

Reaper 6.72 
Windows 10 x64 
AMD 5950x CPU
RME RayDAT audio interface

**Comment by sdatkinson** [comment]
Thanks for the bug! I assume this is using a WaveNet-based model (you can check the `config.json` for the model, but unless you've changed any of the default settings on the trainer this'll probably be "yes").

The cause is that the internal state of the net has to go through ~8192 samples (its receptive field) to equilibrate.  We can fix this either by computing what that state _should_ be (if the inputted signal were zeroes) or by just muting those samples while it's equilibrating.

I thought that I had implemented this...checking, I see it [here](https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/main/NeuralAmpModeler/dsp/wavenet.cpp#L380), but I guess I commented it out. I don't remember why I did that, but that'd be the first place to check.

Flagging this as a potential good first issue in case the fix really is that simple :)
